QisTetiliMultiShop/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace QisTetiliMultiShop.Models
{
    public class Category : BaseModel
    {
        [Required]
        [MaxLength(25, ErrorMessage = "Max length is 25")]
        [MinLength(2, ErrorMessage = "Min length is 2")]
        public string Name { get; set; } = null!;
        public string Image { get; set; } = null!;
        public ICollection<Product>? Products { get; set; }

    }
}

QisTetiliMultiShop/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QisTetiliMultiShop.Areas.Admin.ViewModel;
using QisTetiliMultiShop.DAL;
using QisTetiliMultiShop.Models;
using QisTetiliMultiShop.Utilities.Extensions;

namespace QisTetiliMultiShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;

        public CategoryController(AppDbContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            int limit = 4;
            double count = await _db.Categories.CountAsync();
            if (count != 0)
            {
                if (page > (int)Math.Ceiling(count / limit) || page <= 0)
                {
                    return BadRequest();
                }
            }
            
            List<Category> CategoryList = await _db.Categories.Skip((page - 1) * limit).Take(limit).Include(x=>x.Products).ToListAsync();
            PaginationVM<Category> paginationVM = new PaginationVM<Category>
            {
                Items = CategoryList,
                TotalPage = (int)Math.Ceiling(count / limit),
                CurrentPage = page,
                Limit = limit
            };
            return View(paginationVM);
        }


        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryVM categoryVM)
        {
            if (!ModelState.IsValid)
            {
                return View();

            }
            bool result = await _db.Categories.IgnoreQueryFilters().AnyAsync(x => x.Name == categoryVM.Name);
            if (result)
            {
                ModelState.AddModelError("Name", "Already exists.");
                return View();
            }
            if (!categoryVM.File.CheckFileSize(2))
            {
                ModelState.AddModelError("File", "Max file size is 2MB.");
                return View();
            }
            if (!categoryVM.File.CheckFileType("image"))
            {
                ModelState.AddModelError("File", "Only image files supported.");
                return View();
            }
            Category category = new Category { Name = categoryVM.Name, Image = await categoryVM.File.CreateFileAsync(_env.WebRootPath, "assets", "img") };
            await _db.Categories.AddAsync(category);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Update(int id)
        {

            if (id <= 0)
            {
                return BadRequest();
            }
            Category category = await _db.Categories.FirstOrDefaultAsync(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            UpdateCategoryVM categoryVM = new UpdateCategoryVM
            {
                Name = category.Name,
                Products = category.Products,
                Image = category.Image

            };
            return View(categoryVM);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateCategoryVM newCategory)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            Category oldCategory = await _db.Categories.FirstOrDefaultAsync(x => x.Id == id);
            if (oldCategory == null) return NotFound();

            bool result = await _db.Categories.IgnoreQueryFilters().AnyAsync(x => x.Name == newCategory.Name && x.Id != id);
            if (result)
            {
                ModelState.AddModelError("Name", "This name already used in other category");
                return View();

            }
            if (newCategory.File is not null)
            {
                if (!newCategory.File.CheckFileType("image"))
                {
                    ModelState.AddModelError("Photo", "You need to choose image file.");
                    return View(oldCategory);
                }
                if (!newCategory.File.CheckFileSize(2))
                {
                    ModelState.AddModelError("Photo", "You need to choose up to 2MB.");
                    return View(oldCategory);
                }
                string newimage = await newCategory.File.CreateFileAsync(_env.WebRootPath, "assets", "img");
                oldCategory.Image.Delete(_env.WebRootPath, "assets", "img");
                oldCategory.Image = newimage;
            }
            oldCategory.Name = newCategory.Name;

            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        public async Task<ActionResult> Delete(int id)
        {

            Category category = await _db.Categories.FirstOrDefaultAsync(x => x.Id == id);
            if (category is null) return NotFound();

            //slide.Image.Delete(_env.WebRootPath, "assets", "img");
            //_db.Slides.Remove(slide);

            category.DeletedAt = DateTime.Now;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Detail(int id)
        {
            if (id <= 0)
            {
                return BadRequest();
            }
            Category category = await _db.Categories
            .Include(x => x.Products)
                .ThenInclude(x => x.ProductColors)
                    .ThenInclude(x => x.Color)
            .Include(x => x.Products)
                .ThenInclude(x => x.ProductImages)
            .FirstOrDefaultAsync(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
    }
}

QisTetiliMultiShop/Areas/Admin/Controllers/SlideController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QisTetiliMultiShop.Areas.Admin.ViewModel;
using QisTetiliMultiShop.DAL;
using QisTetiliMultiShop.Models;
using QisTetiliMultiShop.Utilities.Extensions;

namespace QisTetiliMultiShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlideController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;
        public SlideController(AppDbContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            int limit = 4;
            double count = await _db.Slides.CountAsync();
            if (count != 0)
            {
                if (page > (int)Math.Ceiling(count / limit) || page <= 0)
                {
                    return BadRequest();
                }
            }
            List<Slide> SlideList = await _db.Slides.Skip((page - 1) * limit).Take(limit).ToListAsync();

            PaginationVM<Slide> paginationVM = new PaginationVM<Slide>
            {
                Items = SlideList,
                TotalPage = (int)Math.Ceiling(count / limit),
                CurrentPage = page,
                Limit = limit
            };
            return View(paginationVM);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateSlideVM slideVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (await _db.Slides.AnyAsync(x=>x.Order == slideVM.Order))
            {
                slideVM.Order = (await _db.Slides.OrderByDescending(x => x.Order).FirstOrDefaultAsync()).Order+1;
            }
            if (!slideVM.File.CheckFileSize(2))
            {
                ModelState.AddModelError("File", "Max file size is 2MB.");
                return View();
            }
            if (!slideVM.File.CheckFileType("image"))
            {
                ModelState.AddModelError("File", "Only image files supported.");
                return View();
            }

            Slide slide = new Slide
            {
                Title = slideVM.Title,
                Description = slideVM.Description,
                Order = slideVM.Order,
                ButtonLink = slideVM.ButtonLink,
                ButtonText = slideVM.ButtonText,
                Image = await slideVM.File.CreateFileAsync(_env.WebRootPath, "assets", "img")
            };


            await _db.Slides.AddAsync(slide);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail(int id)
        {
            Slide slide = await _db.Slides.FirstOrDefaultAsync(x => x.Id == id);
            return View(slide);
        }
        public async Task<ActionResult> Delete(int id)
        {

            Slide slide = await _db.Slides.FirstOrDefaultAsync(x => x.Id == id);
            if (slide is null) return NotFound();

            //slide.Image.Delete(_env.WebRootPath, "assets", "img");
            //_db.Slides.Remove(slide);

            slide.DeletedAt = DateTime.Now;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Slide existed = await _db.Slides.FirstOrDefaultAsync(s => s.Id == id);
            if (existed is null) return NotFound();
            UpdateSlideVM slideVM = new UpdateSlideVM
            {
                Title = existed.Title,
                ButtonLink = existed.ButtonLink,
                ButtonText = existed.ButtonText,
                Description = existed.Description,
                Order = existed.Order,
                Image = existed.Image,

            };

            return View(slideVM);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateSlideVM slideVM)
        {

            Slide existed = await _db.Slides.FirstOrDefaultAsync(s => s.Id == id);
            if (existed is null) return NotFound();

            if (!ModelState.IsValid)
            {
                return View(existed);
            }

            if (slideVM.File is not null)
            {
                bool result = _db.Slides.Any(s => s.Order < 0);
                if (result)
                {
                    ModelState.AddModelError("Order", "Order can't be smaller than 0.");
                    return View(existed);
                }
                if (await _db.Slides.AnyAsync(x => x.Order == slideVM.Order))
                {
                    slideVM.Order = (await _db.Slides.OrderByDescending(x => x.Order).FirstOrDefaultAsync()).Order + 1;
                }
                if (!slideVM.File.CheckFileType("image"))
                {
                    ModelState.AddModelError("Photo", "You need to choose image file.");
                    return View(existed);
                }
                if (!slideVM.File.CheckFileSize(2))
                {
                    ModelState.AddModelError("Photo", "You need to choose up to 2MB.");
                    return View(existed);
                }
                string newimage = await slideVM.File.CreateFileAsync(_env.WebRootPath, "assets", "img");
                existed.Image.Delete(_env.WebRootPath, "assets", "img");
                existed.Image = newimage;
            }

            existed.Title = slideVM.Title;
            existed.ButtonText = slideVM.ButtonText;
            existed.ButtonLink = slideVM.ButtonLink;
            existed.Description = slideVM.Description;
            existed.Order = slideVM.Order;

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

QisTetiliMultiShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QisTetiliMultiShop.DAL;
using QisTetiliMultiShop.Models;
using QisTetiliMultiShop.ViewModels;

namespace QisTetiliMultiShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _db;


        public ProductController(AppDbContext context)
        {
            _db = context;
        }


        public IActionResult Detail(int id)
        {
            if (id <= 0) return BadRequest();

            Product product = _db.Products
                .Include(x => x.Category)
                .Include(x => x.ProductImages)
                .Include(x => x.ProductColors).ThenInclude(pt => pt.Color)
                .FirstOrDefault(x => x.Id == id);
            if (product == null) return NotFound();


            ProductVM vm = new ProductVM
            {
                Product = product,
                RelatedProducts = _db.Products.Where(p => p.Category.Id == product.CategoryId && p.Id != product.Id).Include(x => x.ProductImages).ToList(),
            };


            return View(vm);
        }
    }
}

QisTetiliMultiShop/Areas/Admin/Views/Category/Create.cshtml
@model CreateCategoryVM
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Slide</h4>

            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name">Title</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span class="text-danger fs-6 fst-italic" asp-validation-for="Name"></span>
                </div>

                
                
                <div class="form-group">
                    <label asp-for="File">Photo</label>
                    <input asp-for="File" class="form-control" placeholder="Upload Photo">
                    <span class="text-danger fs-6 fst-italic" asp-validation-for="File"></span>

                </div>





                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button asp-action="Index" asp-controller="Slide" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>

QisTetiliMultiShop/Areas/Admin/Views/Category/Detail.cshtml
@model Category
<div class="d-flex justify-content-center">
    <p class="btn btn-dark btn-lg ">@Model.Name <br><br> Product Count: @Model.Products.Count()</p>
</div>
<div class="product-box d-flex justify-content-evenly flex-wrap align-content-around">

    @foreach (var item in Model.Products)
    {
        <div class="card" style="width: 18rem;">
            <img src="~/assets/images/website-images/@item.ProductImages.FirstOrDefault(x=>x.IsPrimary==true).Url" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <p class="card-text">Description: @item.Description</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">SKU: @item.SKU</li>
                <li class="list-group-item">
                    Tags:
                    @foreach (var tag in item.ProductColors)
                    {
                        <a>@tag.Color.Name</a>
                    }
                </li>
                <li class="list-group-item">$@item.Price</li>
            </ul>
            <div class="card-body">
                <a asp-area="" asp-controller="Product" asp-action="Details" asp-route-id="@item.Id" class="card-link btn btn-dark btn-lg">Product page</a>
            </div>
        </div>
    }



</div>

QisTetiliMultiShop/Areas/Admin/Views/Category/Index.cshtml
@model PaginationVM<Category>
@{
    int count = 0;
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h4 class="card-title">Slide List</h4>
                <a asp-action="Create" class="btn btn-inverse-success btn-fw "><i class="mdi mdi-plus-circle-outline"></i> <h6>Create</h6></a>
            </div>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Order</th>
                            <th class="d-flex justify-content-end"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            count++;
                            <tr>
                                <td>@count</td>
                                <td>
                                    <img style=" width:150px; height:150px; object-fit:contain" src="~/assets/img//@item.Image"
                                         alt="Inner Image" />
                                </td>
                                <td>@item.Name</td>
                                <td class="text-success"> @item.Products.Count()</td>
                                <td class="d-flex justify-content-end" style=" height:200px; ">
                                    <a asp-action="Detail" asp-route-id="@item.Id" class="btn btn-inverse-primary btn-fw" style="display: inline-flex; align-items: center; margin-left: 6px; ">
                                        <i class="mdi mdi-information-outline"></i> <span style="margin-top: -1px; margin-left: 3px">Details</span>
                                    </a>



                                    <a asp-action="Update" asp-route-id="@item.Id" class="btn btn-inverse-warning btn-fw" style="display: inline-flex; align-items: center; margin-left: 6px;">
                                        <i class="mdi mdi-pencil"></i> <span style="margin-top: -1px; margin-left: 3px">Update</span>
                                    </a>

                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-inverse-danger btn-fw" style="display: inline-flex; align-items: center; margin-left: 6px;">
                                        <i class="mdi mdi-delete"></i> <span style="margin-top: -1px; margin-left: 3px">Delete</span>
                                    </a>

                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item  @(1>=Model.CurrentPage ? "disabled " : "")">
                    <a class="page-link" asp-route-page="@(Model.CurrentPage-1)" tabindex="-1">Previous</a>
                </li>
                @for (int i = 0; i < Model.TotalPage; i++)
                {
                    <li class="page-item @(i==Model.CurrentPage-1? "disabled active": "")"><a class="page-link" asp-route-page="@(i+1)">@(i + 1)</a></li>

                }
                <li class="page-item  @(Model.TotalPage<=Model.CurrentPage ? "disabled " : "")">

                    <a class="page-link" asp-route-page="@(Model.CurrentPage+1)">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</div>

QisTetiliMultiShop/Areas/Admin/Views/Category/Update.cshtml
@model UpdateCategoryVM
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Category</h4>

            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span class="text-danger fs-6 fst-italic" asp-validation-for="Name"></span>
                </div>

                
                <div class="form-group">
                    <label asp-for="File">Photo</label>
                    <input asp-for="File" class="form-control" placeholder="Upload Photo">
                    <span class="text-danger fs-6 fst-italic" asp-validation-for="File"></span>

                </div>





                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button asp-action="Index" asp-controller="Slide" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}